### ISSUE TITLE
Connection Limits / Prioritization

### ISSUE THREAD

**Issue by cyberjunk** [dioptre/tracker#2]
Implement these overload-protection features from NGINX:

1) Allow defining the maximum of total accepted TCP/HTTPS connections
2) Allow defining maximum connections per route
3) From our API/SSO/MS NGINX config: Return HTTP "503" with header "Retry-After: 1" and body "Try again. Maximum clients reached on this node." in case a route limit has been reached (other nodes might still have capacity)

Then:
Leave some reserved connection slots for /ping, e.g.:
On NGINX it'S like: Maximum accepted 2048, maximum of 2000 for /api/, leaves 48 slots for /ping/ (and for returning the 503 overloaded mentioned above).

Necessary for:
Making sure "/ping" still works on an overloaded system. Otherwise AWS ALB HealthCheck tends to accidentially take down heavy-loaded-containers making the load-situation even worse (next one fails, then being taken down etc.). So the heath check (/ping/) needs some extra slots/prioritization etc.)

----------------------

Some sources:

Connection-Limits in Go: 
https://stackoverflow.com/questions/22625367/how-to-limit-the-connection-count-of-an-http-server-implemented-in-go

HTTP "Retry-After": 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After

**Comment by dioptre** [comment]
Yes for ref too:

https://pauladamsmith.com/blog/2016/04/max-clients-go-net-http.html

**Comment by cyberjunk** [comment]
A bit more abstract (not regarding connections etc.)

A bit of capacity must be reserved for:

1) Responses to /ping
2) Telling clients that the node is at its limits

(1) is important to prevent AWS from taking off the heavy loaded nodes
(2) is to turn undefined ELB 502 errors into defined HTTP 503 overloaded errors

**Comment by dioptre** [comment]
Ok so de we queue the responses? or just 503? Sounds like 503?

**Comment by cyberjunk** [comment]
>> Ok so de we queue the responses? or just 503? Sounds like 503?

Just 503 and 'Retry-After' header (if the defined limits of a route, e.g. /tr/ are reached)

**Comment by dioptre** [comment]
Ok gotta think best way to implement this. Not sure I like what I've seen so far.

**Comment by dioptre** [comment]
done
