### ISSUE TITLE
Feature Parity with NGINX

### ISSUE THREAD

**Issue by cyberjunk** [dioptre/tracker#5]
Hey @dioptre ,

leaving you a list of NGINX tweaked settings here. We don't need to have a config value for each of them in the tracker (some might come handy). In most cases it would be enough to know what the Go HTTP server value is and if it's OK for our purpose. Woud like to clarify this before switching from NGINX to Go.

### Timeouts / Related

| Setting                       | NGINX           |   Go/Tracker   |
|-----------------------|---------------|---------------|
| send_timeout             |   40s              |                      |
| client_header_timeout|   40s              |                      |
| client_body_timeout   |   40s              |                      |
| keepalive_timeout      |   20s              |                      |
| keepalive_requests     |  1000            |                      |
| reset_timedout_connection | on       |                       |

### Sizes / Limits
| Setting                              | NGINX           |   Go/Tracker   |
|----------------------------|---------------|---------------|
| client_body_buffer_size       |   8k              |                      |
| client_header_buffer_size    |   1k                |                      |
| client_max_body_size          |   8m              |                      |
| large_client_header_buffers |   4   8k          |                      |

### Compression
Our NGINX compresses all responses larger than 512 bytes and having the listed MIME type. Does tracker have any compression yet?

* text/plain
* text/css
* application/json
* application/javascript
* text/xml
* application/xml
* application/xml+rss
* text/javascript

### Stats Page
There is a stats page in NGINX which shows how many clients are connected etc. I noticed you started something similar in the tracker. Could you may be please add the amount of connected clients there?

### Early Termination of Trash Connections
NGINX kills a connection on TCP level if it tries to access a completely invalid route (defaultcase at the end, e.g. not starting with /api/ respectively /tr/ or others here etc.). Since we use this for our backends which are only accessed by our own frontends, we can assume anything that's trying a complete trash route as malicious or at least unwanted/external (likely backdoor-scanner/bots/etc.) and we don't want to waste our resources on keeping such connections open.

**Comment by dioptre** [comment]
Most of this is done and in config file. Will close for now.
