### ISSUE TITLE
Allow to use 'X-Forwarded-For' as real IP in limiting

### ISSUE THREAD

**Issue by cyberjunk** [dioptre/tracker#6]
On AWS the TCP connections come from a private network IP which is owned by the ALB.
Any sort of limiting on this IP would turn out contra-productive.
Instead any sort of IP based limits should apply to the 'X-Forwarded-For' IP.

**Comment by dioptre** [comment]
That fixed?

**Comment by cyberjunk** [comment]
>> That fixed?

IDK, have to check.
Have you changed something regarding this?

May be add a configuration option which allows to switch between using the real tcp endpoint IP or instead the 'X-Forwarded-For' IP in all queries/logging?

**Comment by cyberjunk** [comment]
Just noticed you did exactly that with the 'getIP()' functions.
Looking good, expect it to work...

**Comment by cyberjunk** [comment]
Yes, it's fixed.
Our sfpla.ips table on AWS is full on real IP addresses of clients now.
No more AWS ALB IPs there.
