### ISSUE TITLE
Tracker discards 'topic' value from NATS message

### ISSUE THREAD

**Issue by cyberjunk** [dioptre/tracker#7]
The sfpla.logs table has a 'topic' column.
However, the tracker ignores this value when inserting a record to DB.

See:
https://github.com/dioptre/tracker/blob/2944b222d7996699697742b5535ba4d42fdf587b/cassandra.go#L177

**Comment by dioptre** [comment]
this should be passed as id

**Comment by dioptre** [comment]
btw added a fallback for this one

**Comment by dioptre** [comment]
removed it again as created a redundancy

**Comment by cyberjunk** [comment]
Ok, this works.
