### ISSUE TITLE
'ltime' field in logs is alwas 00:00:00.000000000

### ISSUE THREAD

**Issue by cyberjunk** [dioptre/tracker#8]
Transmitted 'ltime' logging value looks like this when leaving NodeJS to NATS:

>> "ltime":"15:03:02.044652999"

However, any record in sfpla.logs table always ends up as:

>> 00:00:00.000000000

Code looks like it's completely ignoring the transmitted 'ltime' value but instead trying to figure out its own: https://github.com/dioptre/tracker/blob/2944b222d7996699697742b5535ba4d42fdf587b/cassandra.go#L165

**Comment by dioptre** [comment]
this should be ltimenss

**Comment by cyberjunk** [comment]
>> this should be ltimenss

I tried replacing the key 'ltime' by 'ltimenss' (and also 'ltimens'), but the DB value stays '00:00:00.000000000' in any case - this does not seem to work...

Please check again.
It seemed to me that the client sent value is not used at all in tracker anyways.

Also there is 'created' and 'ldate' 'ltime' in the table:
If both are set from backend, this seems redundant....

I expected that 'created' is set from backends when the log entry is created and sent through NATS and 'ldate' and 'ltime' are set by tracker when the insert to DB actually happens, is this correct or wrong?
